### ISSUE TITLE
[API] Add new parameter to let /blockchain/box/unspent endpoints take mempool into consideration

### ISSUE THREAD

**Issue by pulsarz** [ergoplatform/ergo#2144] opened 2024-04-10 18:24 UTC
Right now these endpoints do not take into account the mempool.
Now that fleet has signing capabilities this is something that will most likely be needed for allowing chained txes to work efficiently.

Currently the only known workaround is to fetch the entire mempool and exclude any boxes that appear as an input in the mempool.

We need the ability to fetch unspent boxes for a wallet, build and send a tx based on that and then do the same thing over again without any extra API calls.

**Comment by kushti** [comment] 2024-04-12 08:33
Duplicate of #2093 , done in #2131

**Closed** 2024-05-01 21:44 UTC
