### ISSUE TITLE
Block info `not-found` via api

### ISSUE THREAD

**Issue by daron666** [ergoplatform/ergo#322] opened 2018-06-25 10:30 UTC
There is two block on height 9535 http://88.198.13.202:9052/blocks/at/9535

The first could be obtained through api [here](0075674140dc7360299473f709758ea7cfb189b2ad4fda13a2cc0b81f3c0282a)
The second one will return error message `not-found` instead of block info [here](http://88.198.13.202:9052/blocks/00a5f791e249da164911b98dfcc173cbd88888d27a4e03e6d5d8ca8ca02872bb)

Checked on nodes : `http://88.198.13.202:9052/` and `http://209.97.136.204:9052/`

**Comment by catena2w** [comment] 2018-08-01 13:15
already fixed

**Comment by catena2w** [comment] 2019-03-14 11:50
duplicate of https://github.com/ergoplatform/ergo/issues/629

**Closed by catena2w** 2019-03-14 11:50 UTC
Labels: bug
