### ISSUE TITLE
 Calculated proofHash is not equal to the declared one

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1606] opened 2022-01-31 19:57 UTC
It seems still a proof generated may be dirty (because of parallel modification or a cleanup not fully done? )

from logs: 

ergo-node-mainnet_1  | 03:18:50.833 WARN  [ctor.default-dispatcher-8] o.e.n.h.ErgoHistory$$anon$3 - Error while applying modifier dd563da1f10bedbe66e4d6ea7ee414a20fca34b7f86b1cdfbac5993bf4d76ee8 of type 104, reason: scorex.core.validation.MalformedModifierError: Block sections should correspond to the declared header. header=40a5e179feb0e109d0ae368cae7be8eb7e1b6441cec5eb77ec7928f36c2557eb, id=dd563da1f10bedbe66e4d6ea7ee414a20fca34b7f86b1cdfbac5993bf4d76ee8 
ergo-node-mainnet_1  | 03:18:50.833 WARN  [ctor.default-dispatcher-8] o.e.n.UtxoNodeViewHolder - Can`t apply persistent modifier (id: dd563da1f10bedbe66e4d6ea7ee414a20fca34b7f86b1cdfbac5993bf4d76ee8, contents: ADProofs(Id:dd563da1f10bedbe66e4d6ea7ee414a20fca34b7f86b1cdfbac5993bf4d76ee8,HeaderId:40a5e179feb0e109d0ae368cae7be8eb7e1b6441cec5eb77ec7928f36c2557eb)) to history
ergo-node-mainnet_1  | 03:18:50.836 WARN  [ctor.default-dispatcher-8] o.e.n.state.UtxoState - Error while applying full block with header 40a5e179feb0e109d0ae368cae7be8eb7e1b6441cec5eb77ec7928f36c2557eb to UTXOState with root 23b45daa22300cf29f0adcfd0cd31ce63d30a17d9fd6872ccdfae79e31b8bcec18, reason: java.lang.Error: Calculated proofHash is not equal to the declared one

**Comment by stenolog** [comment] 2024-02-26 23:16
- duplicate of https://github.com/ergoplatform/ergo/issues/1023

**Closed** 2024-02-27 15:38 UTC
Labels: C-bug, P1-high
