### ISSUE TITLE
Node can't establish connection

### ISSUE THREAD

**Issue by travek** [ergoplatform/ergo#828] opened 2019-07-01 18:58 UTC
Hi!

I constantly see that my mainnet node can't establish connections and that causes that I can't  mine (Hrate =0 on miner).

21:57:53.581 DEBUG [tor.default-dispatcher-21] o.e.n.UtxoNodeViewHolder - Cache size before: 1
21:57:53.581 INFO  [tor.default-dispatcher-22] o.e.n.ErgoNodeViewSynchronizer - Got 1 modifiers of type 102 from remote connected peer: ConnectedPeer(ConnectionId(remote=/51.75.52.63:9030, local=/192.168.1.67:62345, direction=Outgoing))
21:57:53.581 INFO  [tor.default-dispatcher-22] o.e.n.ErgoNodeViewSynchronizer - Got 1 modifiers of type 108 from remote connected peer: ConnectedPeer(ConnectionId(remote=/51.75.52.63:9030, local=/192.168.1.67:62345, direction=Outgoing))
21:57:53.581 INFO  [tor.default-dispatcher-21] o.e.n.UtxoNodeViewHolder - Apply modifier 1988810fe703edc929e83198280b30cd32e6d1278f2b9118bc4b5760cb15238d of type 101 to nodeViewHolder
21:57:53.581 DEBUG [tor.default-dispatcher-21] o.e.n.h.ErgoHistory$$anon$3 - Trying to append modifier 1988810fe703edc929e83198280b30cd32e6d1278f2b9118bc4b5760cb15238d of type 101 to history
21:57:53.581 INFO  [tor.default-dispatcher-21] o.e.n.h.ErgoHistory$$anon$3 - New best header 1988810fe703edc929e83198280b30cd32e6d1278f2b9118bc4b5760cb15238d with score 14446498360066048. New height 2615, old height 2614
21:57:53.644 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/5.189.162.66:9030, local=/192.168.1.67:55204, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/5.189.162.66:9030, local=/192.168.1.67:55204, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-10] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/5.189.162.66:9030, local=/192.168.1.67:55204, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/134.209.236.185:9030, local=/192.168.1.67:56327, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/134.209.236.185:9030, local=/192.168.1.67:56327, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/134.209.236.185:9030, local=/192.168.1.67:56327, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/217.150.95.31:9030, local=/192.168.1.67:52667, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/217.150.95.31:9030, local=/192.168.1.67:52667, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/217.150.95.31:9030, local=/192.168.1.67:52667, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-10] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.93.83:9030, local=/192.168.1.67:54356, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-10] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.93.83:9030, local=/192.168.1.67:54356, direction=Outgoing)
21:57:53.644 INFO  [tor.default-dispatcher-10] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.93.83:9030, local=/192.168.1.67:54356, direction=Outgoing)
21:57:53.659 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/195.181.242.189:9030, local=/192.168.1.67:60450, direction=Outgoing)
21:57:53.659 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/195.181.242.189:9030, local=/192.168.1.67:60450, direction=Outgoing)
21:57:53.659 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/195.181.242.189:9030, local=/192.168.1.67:60450, direction=Outgoing)
21:57:53.691 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/134.209.183.15:9030, local=/192.168.1.67:63825, direction=Outgoing)
21:57:53.691 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/134.209.183.15:9030, local=/192.168.1.67:63825, direction=Outgoing)
21:57:53.691 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.75.209:9030, local=/192.168.1.67:52947, direction=Outgoing)
21:57:53.706 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/134.209.183.15:9030, local=/192.168.1.67:63825, direction=Outgoing)
21:57:53.706 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.75.209:9030, local=/192.168.1.67:52947, direction=Outgoing)
21:57:53.706 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.75.209:9030, local=/192.168.1.67:52947, direction=Outgoing)
21:57:53.738 INFO  [tor.default-dispatcher-10] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:58383, direction=Outgoing)
21:57:53.738 INFO  [tor.default-dispatcher-10] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:58383, direction=Outgoing)
21:57:53.738 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:58383, direction=Outgoing)
21:57:53.784 DEBUG [tor.default-dispatcher-21] o.e.n.UtxoNodeViewHolder - Going to apply modifications to the state: ProgressInfo(BranchPoint: None,  to remove: List(), to apply: List())
21:57:53.784 DEBUG [tor.default-dispatcher-21] o.e.n.UtxoNodeViewHolder - Cache size after: 0
21:57:53.784 DEBUG [tor.default-dispatcher-21] o.e.n.UtxoNodeViewHolder - Cache size before: 1

Why is it happening ? and how to fix ?

**Comment by travek** [comment] 2019-07-01 19:01
Additional logs
......

22:01:11.705 INFO  [tor.default-dispatcher-12] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/134.209.236.185:9030, local=/192.168.1.67:56327, direction=Outgoing)
22:01:11.705 INFO  [ctor.default-dispatcher-5] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/64.79.110.194:9030, local=/192.168.1.67:63407, direction=Outgoing)
22:01:11.705 INFO  [tor.default-dispatcher-14] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/78.46.93.239:9030, local=/192.168.1.67:64209, direction=Outgoing)
22:01:11.705 INFO  [tor.default-dispatcher-20] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/195.181.242.189:9030, local=/192.168.1.67:60450, direction=Outgoing)
22:01:11.705 INFO  [tor.default-dispatcher-16] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/51.75.52.63:9030, local=/192.168.1.67:62345, direction=Outgoing)
22:01:11.705 INFO  [ctor.default-dispatcher-7] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/217.150.95.31:9030, local=/192.168.1.67:52667, direction=Outgoing)
22:01:11.705 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/139.59.29.87:9030, local=/192.168.1.67:62884, direction=Outgoing)
22:01:11.705 INFO  [tor.default-dispatcher-13] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/138.68.98.248:9030, local=/192.168.1.67:62346, direction=Outgoing)
22:01:11.720 INFO  [ctor.default-dispatcher-2] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/118.189.191.191:9030, local=/192.168.1.67:62344, direction=Outgoing)
22:01:11.720 INFO  [ctor.default-dispatcher-9] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/167.86.94.121:9030, local=/192.168.1.67:62650, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/116.203.93.83:9030, local=/192.168.1.67:54356, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-18] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/116.203.93.83:9030, local=/192.168.1.67:54356, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-24] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/116.203.75.209:9030, local=/192.168.1.67:52947, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-21] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/134.209.183.15:9030, local=/192.168.1.67:63825, direction=Outgoing)
22:01:11.720 INFO  [ctor.default-dispatcher-4] o.e.n.UtxoNodeViewHolder - Apply modifier 00557127dbf17f0b11e68bb99e6b9f0b6c350cc3e6ce0f6b983f1fc49564df23 of type 104 to nodeViewHolder
22:01:11.720 INFO  [ctor.default-dispatcher-6] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/5.189.162.66:9030, local=/192.168.1.67:55204, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-26] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/108.61.206.113:9030, local=/192.168.1.67:61238, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/185.246.85.32:9020, local=/192.168.1.67:54052, direction=Outgoing)
22:01:11.720 INFO  [ctor.default-dispatcher-8] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/185.80.128.46:9030, local=/192.168.1.67:53515, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-17] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/67.205.163.32:9030, local=/192.168.1.67:56596, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-10] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/144.202.66.220:9030, local=/192.168.1.67:55485, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-15] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:58383, direction=Outgoing)
22:01:11.720 INFO  [tor.default-dispatcher-12] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/134.209.236.185:9030, local=/192.168.1.67:56327, direction=Outgoing)
22:01:11.720 INFO  [ctor.default-dispatcher-5] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/64.79.110.194:9030, local=/192.168.1.67:63407, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-14] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/78.46.93.239:9030, local=/192.168.1.67:64209, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-20] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/195.181.242.189:9030, local=/192.168.1.67:60450, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-16] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/51.75.52.63:9030, local=/192.168.1.67:62345, direction=Outgoing)
22:01:11.736 INFO  [ctor.default-dispatcher-7] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/217.150.95.31:9030, local=/192.168.1.67:52667, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-22] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/139.59.29.87:9030, local=/192.168.1.67:62884, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-13] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/138.68.98.248:9030, local=/192.168.1.67:62346, direction=Outgoing)
22:01:11.736 INFO  [ctor.default-dispatcher-2] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/118.189.191.191:9030, local=/192.168.1.67:62344, direction=Outgoing)
22:01:11.736 INFO  [ctor.default-dispatcher-9] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/167.86.94.121:9030, local=/192.168.1.67:62650, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-24] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/116.203.75.209:9030, local=/192.168.1.67:52947, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-21] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/134.209.183.15:9030, local=/192.168.1.67:63825, direction=Outgoing)
22:01:11.736 INFO  [tor.default-dispatcher-26] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/108.61.206.113:9030, local=/192.168.1.67:61238, direction=Outgoing)
22:01:11.752 INFO  [tor.default-dispatcher-19] o.e.local.ErgoMiner - New candidate with msg bd6c56f57f141079587d00b02b93ea85745c241080918755c795f0d73402fd7a generated
22:01:11.752 INFO  [tor.default-dispatcher-26] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/108.61.206.113:9030, local=/192.168.1.67:61238, direction=Outgoing)
22:01:11.752 INFO  [tor.default-dispatcher-26] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/108.61.206.113:9030, local=/192.168.1.67:61238, direction=Outgoing)
22:01:11.892 INFO  [tor.default-dispatcher-19] o.e.local.MempoolAuditor - Initiating cleanup. Switching to working mode
22:01:11.892 INFO  [tor.default-dispatcher-19] o.e.local.MempoolAuditor - Cleanup done. Switching to awaiting mode
22:01:12.017 INFO  [tor.default-dispatcher-13] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/185.80.128.46:9030, local=/192.168.1.67:53515, direction=Outgoing)
22:01:12.017 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/185.80.128.46:9030, local=/192.168.1.67:53515, direction=Outgoing)

**Comment by travek** [comment] 2019-07-02 18:45
Today the sitiation looks better in my opinion. Logs below.

I post addiitonal issue in Miner thread. Miner hashrate seems to be low and floating, RAM is  ot fully utilized. 
And I can't understand why My node didn't receive any miner rewar for the last 2 days - checking my account balance through APIs. Seems strange for me but may be there's an explanations for this.

Logs:
21:41:56.945 DEBUG [ctor.default-dispatcher-2] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,b0244dfc267baca974a4caee06120321562784303a8a688976ae56170e4d175b)..(101,8dee6ae0a0fcc43475d2b21a201e84aacd85a3ccca1898410dabb0a25435b640)]
21:41:56.945 INFO  [ctor.default-dispatcher-2] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/167.86.94.121:9030, local=/192.168.1.67:53090, direction=Outgoing)
21:42:07.628 INFO  [ctor.default-dispatcher-7] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/78.46.93.239:9030, local=/192.168.1.67:54958, direction=Outgoing)
21:42:07.695 INFO  [ctor.default-dispatcher-5] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:61735, direction=Outgoing)
21:42:07.758 INFO  [tor.default-dispatcher-13] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/195.181.242.189:9030, local=/192.168.1.67:57672, direction=Outgoing)
21:42:07.772 DEBUG [ctor.default-dispatcher-7] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/78.46.93.239:9030, local=/192.168.1.67:54958, direction=Outgoing)) having starting points [(101,acb75746bec25e6f1fd8f482a4af2b932e841833fb1b1ce82754e7cc67d24d17)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]. Comparison result is Equal. Sending extension of length 400
21:42:07.772 DEBUG [ctor.default-dispatcher-7] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,7bfa7c584399bd1f8d36a727223b0c425f59d4771136e4018c019379ec9e3b32)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]
21:42:07.778 DEBUG [ctor.default-dispatcher-7] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:61735, direction=Outgoing)) having starting points [(101,acb75746bec25e6f1fd8f482a4af2b932e841833fb1b1ce82754e7cc67d24d17)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]. Comparison result is Equal. Sending extension of length 400
21:42:07.778 DEBUG [ctor.default-dispatcher-7] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,7bfa7c584399bd1f8d36a727223b0c425f59d4771136e4018c019379ec9e3b32)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]
21:42:07.788 DEBUG [ctor.default-dispatcher-7] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/195.181.242.189:9030, local=/192.168.1.67:57672, direction=Outgoing)) having starting points [(101,acb75746bec25e6f1fd8f482a4af2b932e841833fb1b1ce82754e7cc67d24d17)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]. Comparison result is Equal. Sending extension of length 400
21:42:07.788 DEBUG [ctor.default-dispatcher-7] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,7bfa7c584399bd1f8d36a727223b0c425f59d4771136e4018c019379ec9e3b32)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]
21:42:09.879 INFO  [tor.default-dispatcher-19] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/167.86.94.121:9030, local=/192.168.1.67:53090, direction=Outgoing)
21:42:09.879 INFO  [ctor.default-dispatcher-6] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/78.46.93.239:9030, local=/192.168.1.67:54958, direction=Outgoing)
21:42:17.665 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/134.209.183.15:9030, local=/192.168.1.67:51887, direction=Outgoing)
21:42:17.706 DEBUG [tor.default-dispatcher-13] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/134.209.183.15:9030, local=/192.168.1.67:51887, direction=Outgoing)) having starting points [(101,acb75746bec25e6f1fd8f482a4af2b932e841833fb1b1ce82754e7cc67d24d17)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]. Comparison result is Equal. Sending extension of length 400
21:42:17.706 DEBUG [tor.default-dispatcher-13] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,7bfa7c584399bd1f8d36a727223b0c425f59d4771136e4018c019379ec9e3b32)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]
21:42:25.820 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/198.204.251.98:9030, local=/192.168.1.67:64408, direction=Outgoing)
21:42:25.940 DEBUG [tor.default-dispatcher-25] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/198.204.251.98:9030, local=/192.168.1.67:64408, direction=Outgoing)) having starting points [(101,0000000000000000000000000000000000000000000000000000000000000000)..(101,a426ac9c6a1a4334c071d3e00ff045d309e1a4397b2ce080bd90b54e880081ba)]. Comparison result is Fork. Sending extension of length 400
21:42:25.940 DEBUG [tor.default-dispatcher-25] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,b0244dfc267baca974a4caee06120321562784303a8a688976ae56170e4d175b)..(101,8dee6ae0a0fcc43475d2b21a201e84aacd85a3ccca1898410dabb0a25435b640)]
21:42:25.940 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/198.204.251.98:9030, local=/192.168.1.67:64408, direction=Outgoing)
21:42:26.945 INFO  [tor.default-dispatcher-13] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/167.86.94.121:9030, local=/192.168.1.67:53090, direction=Outgoing)
21:42:26.948 DEBUG [ctor.default-dispatcher-2] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/167.86.94.121:9030, local=/192.168.1.67:53090, direction=Outgoing)) having starting points []. Comparison result is Younger. Sending extension of length 400
21:42:26.948 DEBUG [ctor.default-dispatcher-2] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,b0244dfc267baca974a4caee06120321562784303a8a688976ae56170e4d175b)..(101,8dee6ae0a0fcc43475d2b21a201e84aacd85a3ccca1898410dabb0a25435b640)]
21:42:26.948 INFO  [ctor.default-dispatcher-2] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to ConnectionId(remote=/167.86.94.121:9030, local=/192.168.1.67:53090, direction=Outgoing)
21:42:27.662 INFO  [ctor.default-dispatcher-6] s.c.n.PeerConnectionHandler - Received message MessageSpec(65: Sync) from ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:61735, direction=Outgoing)
21:42:27.670 DEBUG [ctor.default-dispatcher-6] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/116.203.44.163:9030, local=/192.168.1.67:61735, direction=Outgoing)) having starting points [(101,acb75746bec25e6f1fd8f482a4af2b932e841833fb1b1ce82754e7cc67d24d17)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]. Comparison result is Equal. Sending extension of length 400
21:42:27.670 DEBUG [ctor.default-dispatcher-6] o.e.n.ErgoNodeViewSynchronizer - Extension ids: [(101,7bfa7c584399bd1f8d36a727223b0c425f59d4771136e4018c019379ec9e3b32)..(101,ea144224270e97ca2c9348670abcb744077e2d34d0279264ab707e400485fc9d)]
21:42:29.884 INFO  [ctor.default-dispatcher-2] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/51.75.52.63:9030, local=/192.168.1.67:54959, direction=Outgoing)
21:42:29.884 INFO  [ctor.default-dispatcher-5] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/78.141.207.121:9030, local=/192.168.1.67:64840, direction=Outgoing)
21:42:29.884 INFO  [tor.default-dispatcher-13] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/67.205.163.32:9030, local=/192.168.1.67:56308, direction=Outgoing)
21:42:29.884 INFO  [tor.default-dispatcher-19] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/139.59.29.87:9030, local=/192.168.1.67:54956, direction=Outgoing)
21:42:29.884 INFO  [tor.default-dispatcher-25] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/67.205.165.106:9030, local=/192.168.1.67:59163, direction=Outgoing)
21:42:29.884 INFO  [ctor.default-dispatcher-7] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to ConnectionId(remote=/118.189.191.191:9030, local=/192.168.1.67:54961, direction=Outgoing)

**Comment by oskin1** [comment] 2019-07-03 03:34
Please provide a response from `/info` API route of your node.

**Comment by travek** [comment] 2019-07-03 16:11
{
  "currentTime" : 1562170269799,
  "name" : "TRAVEK-Ergo-Mainnet-node",
  "stateType" : "utxo",
  "difficulty" : 185435213004800,
  "bestFullHeaderId" : "b26b2cc890768f11d343eee5ed860a995234404cd16f24ccbb3569853c8fdd86",
  "bestHeaderId" : "b26b2cc890768f11d343eee5ed860a995234404cd16f24ccbb3569853c8fdd86",
  "peersCount" : 20,
  "unconfirmedCount" : 2,
  "appVersion" : "3.0.1",
  "stateRoot" : "30e82c62ecc66952562cf7b142207112edf6a692fbe0718489ab95a2b8ad9b0e0f",
  "genesisBlockId" : "b0244dfc267baca974a4caee06120321562784303a8a688976ae56170e4d175b",
  "previousFullHeaderId" : "9c07b7ff86de9563875ad263aaa0234c22412dda9a6ad0f002631e61b87d051a",
  "fullHeight" : 4040,
  "headersHeight" : 4040,
  "stateVersion" : "b26b2cc890768f11d343eee5ed860a995234404cd16f24ccbb3569853c8fdd86",
  "fullBlocksScore" : 203610810226835456,
  "launchTime" : 1562169836090,
  "headersScore" : 203610810226835456,
  "parameters" : {
    "outputCost" : 100,
    "tokenAccessCost" : 100,
    "maxBlockCost" : 1000000,
    "height" : 3072,
    "maxBlockSize" : 524288,
    "dataInputCost" : 100,
    "blockVersion" : 1,
    "inputCost" : 2000,
    "storageFeeFactor" : 1250000,
    "minValuePerByte" : 360
  },
  "isMining" : true
}

**Comment by oskin1** [comment] 2019-07-03 16:19
Seems you're synched with the network. Temporal synchronization issues caused by block delays fixed by #831.

**Closed by oskin1** 2019-07-03 16:19 UTC
