### ISSUE TITLE
bestFullBlock and bestHeader are not linearized 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#328] opened 2018-06-28 09:02 UTC
Potentially bestFullBlock* and bestHeader* variables in ErgoHistory could reference different chains(due to forks), which is counter-intuitive and causing problems in ErgoHistory clients (e.g. nextModifiersToDownload in ToDownloadsProcessor and findCandidate in ErgoModifiersCache, but we need to carefully check all the places where bestFullBlock.header is handled to be sure it is not considered as a part of a best-headers chain).

Possible solutions are: 
1) include "commonBlock" variable to the ErgoHistory interface, which shows a common block of two potentially different chains(one with most work, another with most work and full blocks only). Then client applications can check whether forking happens (by checking commonBlock == fullBlock). 

2) make the only one best chain rule, then bestFullBlock and bestHeader will be linearized. Switching to a better chain will happen only if it contains enough full blocks (full blocks in the better chain have more cumulative weight than the full block of the current chain).

**Comment by catena2w** [comment] 2018-08-01 13:17
We decided to add `bestLinearHeader` link, implemented at https://github.com/ergoplatform/ergo/pull/333

**Comment by catena2w** [comment] 2018-08-01 13:17
duplicate of https://github.com/ergoplatform/ergo/issues/331

**Closed by catena2w** 2018-08-01 13:17 UTC
Labels: bug
