### ISSUE TITLE
Dead letters

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#773] opened 2019-06-06 11:13 UTC
On node startup quite often I see dead letters
```
13:12:09.187 WARN  [ctor.default-dispatcher-3] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
13:12:09.638 WARN  [ctor.default-dispatcher-3] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
13:12:09.678 WARN  [ctor.default-dispatcher-3] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
13:12:10.588 WARN  [ctor.default-dispatcher-6] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
13:12:10.777 WARN  [ctor.default-dispatcher-4] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
13:12:11.194 INFO  [ctor.default-dispatcher-5] o.e.n.UtxoNodeViewHolder - State and history have the same version ceeeaf1a3ef84fd14786fe198c472cc9e45cc44689b624e748afbaf0f499ba9b, no recovery needed.
13:12:11.214 WARN  [ctor.default-dispatcher-3] o.e.n.w.ErgoWalletActor - Initializing wallet in test mode. Switch to secure mode for production usage.
[INFO] [06/06/2019 13:12:11.658] [ergoref-akka.actor.default-dispatcher-2] [akka://ergoref/deadLetters] Message [org.ergoplatform.nodeView.ErgoReadersHolder$Readers] from Actor[akka://ergoref/user/$c#933205789] to Actor[akka://ergoref/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://ergoref/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [06/06/2019 13:12:11.697] [ergoref-akka.actor.default-dispatcher-5] [akka://ergoref/deadLetters] Message [org.ergoplatform.nodeView.ErgoReadersHolder$Readers] from Actor[akka://ergoref/user/$c#933205789] to Actor[akka://ergoref/deadLetters] was not delivered. [2] dead letters encountered. If this is not an expected behavior, then [Actor[akka://ergoref/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
13:12:11.743 INFO  [ctor.default-dispatcher-4] s.c.n.PeerConnectionHandler - Send message MessageSpec(65: Sync) to /159.65.139.199:9020
13:12:12.078 INFO  [ctor.default-dispatcher-5] s.c.n.NetworkController - Connecting to peer: PeerInfo(PeerSpec(unknown,Version(0,0,1),unknown-/206.189.130.185:9020,Some(/206.189.130.185:9020),List()),0,None)
13:12:12.225 INFO  [ctor.default-dispatcher-5] s.c.n.NetworkController - New outgoing connection to /206.189.130.185:9020 established (bound to local /88.198.13.202:58528)
13:12:12.226 INFO  [ctor.default-dispatcher-4] s.c.n.PeerConnectionHandler - Handshake sent to /206.189.130.185:9020
13:12:12.371 INFO  [ctor.default-dispatcher-2] s.c.n.PeerConnectionHandler - Got a Handshake from /206.189.130.185:9020
[INFO] [06/06/2019 13:12:12.608] [ergoref-akka.actor.default-dispatcher-5] [akka://ergoref/deadLetters] Message [org.ergoplatform.nodeView.ErgoReadersHolder$Readers] from Actor[akka://ergoref/user/$c#933205789] to Actor[akka://ergoref/deadLetters] was not delivered. [3] dead letters encountered. If this is not an expected behavior, then [Actor[akka://ergoref/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by oskin1** [comment] 2019-06-13 12:19
Caused by #790

**Comment by glasgowm148** [comment] 2022-02-01 12:06
Closing as another issues exists

**Closed by glasgowm148** 2022-02-01 12:06 UTC
Labels: C-bug
